# fly.toml app configuration file generated for openpoll on 2024-03-12T08:13:16+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'openpoll'
primary_region = 'cdg'
swap_size_mb = 1024

[build]

[[mounts]]
  source = 'myapp_data'
  destination = '/data'

[http_service]
  internal_port = 4321
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
